import bcrypt from 'bcryptjs';
import dotenv from 'dotenv';

dotenv.config();

class MockStore {
  constructor() {
    this.users = [];
    this.products = [];
    this.categories = [];
    this.coupons = [];
    this.orders = [];
    this.reviews = [];
    this.rewardTransactions = [];
    this.addresses = [];
    this.init();
  }

  init() {
    this.categories = [
      // MEN
      {
        _id: 'cat_men_1',
        name: 'Ear Studs',
        slug: 'ear-studs',
        gender: 'men',
        image: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=800&q=80',
        description: 'Minimalist & anti-tarnish studs crafted with 18K gold PVD and black onyx accents.',
      },
      {
        _id: 'cat_men_2',
        name: 'Chains',
        slug: 'chains',
        gender: 'men',
        image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80',
        description: 'Statement Cuban and Byzantine chains engineered for modern Indian men.',
      },
      {
        _id: 'cat_men_3',
        name: 'Bracelets',
        slug: 'bracelets',
        gender: 'men',
        image: 'https://images.unsplash.com/photo-1611591475103-4fa1b7765a7f?auto=format&fit=crop&w=800&q=80',
        description: 'Bold cuffs, leather weaves, and steel links that command respect.',
      },
      {
        _id: 'cat_men_4',
        name: 'Belts',
        slug: 'belts',
        gender: 'men',
        image: 'https://images.unsplash.com/photo-1624222247344-550fb60583dc?auto=format&fit=crop&w=800&q=80',
        description: 'Luxury handcrafted full-grain leather belts with brushed platinum & gold buckles.',
      },
      {
        _id: 'cat_men_5',
        name: 'Rings',
        slug: 'rings',
        gender: 'men',
        image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=80',
        description: 'Signet rings, tungsten bands, and obsidian inlays made to last a lifetime.',
      },
      // WOMEN
      {
        _id: 'cat_women_1',
        name: 'Earrings',
        slug: 'earrings',
        gender: 'women',
        image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80',
        description: 'Cascading chandbalis, diamond-cut huggies, and pearl drop earrings.',
      },
      {
        _id: 'cat_women_2',
        name: 'Saree Accessories',
        slug: 'saree-accessories',
        gender: 'women',
        image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=800&q=80',
        description: 'Handcrafted kamarbandhs, pearl saree pins, and heirloom waist brooches.',
      },
      {
        _id: 'cat_women_3',
        name: 'Anklets',
        slug: 'anklets',
        gender: 'women',
        image: 'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?auto=format&fit=crop&w=800&q=80',
        description: 'Delicate water-resistant payals and layered seashell anklets.',
      },
      {
        _id: 'cat_women_4',
        name: 'Jeans Adjuster',
        slug: 'jeans-adjuster',
        gender: 'women',
        image: 'https://images.unsplash.com/photo-1598560917505-59a3ad559071?auto=format&fit=crop&w=800&q=80',
        description: 'Jewelled pearl and golden waist cinchers that double as aesthetic luxury charms.',
      },
      {
        _id: 'cat_women_5',
        name: 'Bracelets & Bangles',
        slug: 'bracelets-bangles',
        gender: 'women',
        image: 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?auto=format&fit=crop&w=800&q=80',
        description: 'Openable kadas, Tennis bracelets, and ethereal charm stacks.',
      },
      {
        _id: 'cat_women_6',
        name: 'Upper Lobe Earrings',
        slug: 'upper-lobe-earrings',
        gender: 'women',
        image: 'https://images.unsplash.com/photo-1600003014755-ba31aa59c4b6?auto=format&fit=crop&w=800&q=80',
        description: 'Hypoallergenic cartilage cuffs, constellation studs, and upper helix crawlers.',
      },
      {
        _id: 'cat_women_7',
        name: 'Rings',
        slug: 'rings',
        gender: 'women',
        image: 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=800&q=80',
        description: 'Solitaire bands, vintage eternity rings, and adjustable statement pieces.',
      },
      {
        _id: 'cat_women_8',
        name: 'Nose Rings',
        slug: 'nose-rings',
        gender: 'women',
        image: 'https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?auto=format&fit=crop&w=800&q=80',
        description: 'Non-piercing clip-on naths and delicate cubic zirconia nose pins.',
      },
    ];

    const adminEmail = (process.env.ADMIN_EMAIL || 'admin@oceanjewel.com').toLowerCase();
    const adminName = process.env.ADMIN_NAME || 'Ocean Jewel Executive';
    const adminPasswordRaw = process.env.ADMIN_PASSWORD;
    const adminHashedPassword = adminPasswordRaw ? bcrypt.hashSync(adminPasswordRaw, 8) : '';
    const userHashedPassword = bcrypt.hashSync('Customer@123', 8);

    this.users = [];

    if (adminHashedPassword) {
      this.users.push({
        _id: 'user_admin_001',
        name: adminName,
        email: adminEmail,
        password: adminHashedPassword,
        phone: '+91 9876543210',
        role: 'admin',
        oceanPoints: 1000,
        createdAt: new Date().toISOString(),
      });
    }

    this.users.push({
      _id: 'user_customer_001',
      name: 'Riya Sharma',
      email: 'riya.sharma@example.com',
      password: userHashedPassword,
      phone: '+91 9123456780',
      role: 'user',
      oceanPoints: 550,
      createdAt: new Date().toISOString(),
    });

    this.addresses = [
      {
        _id: 'addr_001',
        user: 'user_customer_001',
        fullName: 'Riya Sharma',
        phone: '+91 9123456780',
        house: 'Flat 402, Lotus Grand Residences',
        street: 'Koramangala 4th Block',
        area: 'Near Sony World Signal',
        city: 'Bengaluru',
        state: 'Karnataka',
        pincode: '560034',
        landmark: 'Opposite Starbucks',
        addressType: 'HOME',
        isDefault: true,
      },
    ];

    this.rewardTransactions = [
      {
        _id: 'rew_001',
        user: 'user_customer_001',
        points: 50,
        type: 'BONUS',
        description: 'New Member Welcome Bonus',
        balanceAfter: 50,
        createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        _id: 'rew_002',
        user: 'user_customer_001',
        points: 500,
        type: 'EARNED',
        description: 'Earned from Festive Royal Order #OJ-26-441920',
        balanceAfter: 550,
        createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      },
    ];

    this.coupons = [
      {
        _id: 'coup_001',
        code: 'WELCOME10',
        description: '10% discount on your first luxury order',
        discountType: 'percentage',
        discountAmount: 10,
        minOrderAmount: 499,
        maxDiscountAmount: 1000,
        expiryDate: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000).toISOString(),
        usageLimit: 5000,
        usedCount: 14,
        isActive: true,
      },
      {
        _id: 'coup_002',
        code: 'OCEAN20',
        description: '20% off on premium orders above ₹1,499',
        discountType: 'percentage',
        discountAmount: 20,
        minOrderAmount: 1499,
        maxDiscountAmount: 2000,
        expiryDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(),
        usageLimit: 2000,
        usedCount: 38,
        isActive: true,
      },
      {
        _id: 'coup_003',
        code: 'FESTIVE500',
        description: 'Flat ₹500 discount on grand collections above ₹2,499',
        discountType: 'fixed',
        discountAmount: 500,
        minOrderAmount: 2499,
        maxDiscountAmount: 500,
        expiryDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
        usageLimit: 1000,
        usedCount: 22,
        isActive: true,
      },
    ];

    this.products = [
      // MEN
      {
        _id: 'prod_men_1',
        name: 'Vanguard Obsidian Studs',
        slug: 'vanguard-obsidian-studs',
        category: 'Ear Studs',
        subCategory: 'Ear Studs',
        gender: 'men',
        price: 999,
        originalPrice: 1699,
        discount: 41,
        description: 'Engineered from surgical grade 316L stainless steel inlaid with natural volcanic obsidian stone. Waterproof, anti-tarnish, and featherlight for all-day commanding style.',
        shortDescription: 'Natural volcanic obsidian set in anti-tarnish surgical steel.',
        images: [
          'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1600003014755-ba31aa59c4b6?auto=format&fit=crop&w=800&q=80',
        ],
        stock: 25,
        material: '316L Surgical Stainless Steel & Natural Obsidian',
        finish: 'Matte Brushed & High Gloss Stone',
        sizes: ['6mm', '8mm'],
        rating: 4.9,
        numReviews: 48,
        isNewArrival: false,
        isBestseller: true,
        isTrending: true,
        isAntiTarnish: true,
        isActive: true,
        tags: ['Men', 'Studs', 'Obsidian', 'Anti-Tarnish', 'Minimal'],
        createdAt: new Date().toISOString(),
      },
      {
        _id: 'prod_men_2',
        name: 'Ares 7mm Cuban Curb Chain',
        slug: 'ares-7mm-cuban-curb-chain',
        category: 'Chains',
        subCategory: 'Chains',
        gender: 'men',
        price: 1899,
        originalPrice: 3299,
        discount: 42,
        description: 'Diamond-cut heavy links bathed in 18K Real Gold PVD coating. Resists sweat, gym workouts, and pool water without losing its dazzling champagne gold luster.',
        shortDescription: '18K Gold PVD coated heavy Cuban link chain. 100% waterproof.',
        images: [
          'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=800&q=80',
        ],
        stock: 18,
        material: '316L Stainless Steel with 18K Gold PVD Coating',
        finish: 'Mirror Polished Diamond Cut',
        sizes: ['20 inch', '22 inch', '24 inch'],
        rating: 4.8,
        numReviews: 62,
        isNewArrival: false,
        isBestseller: true,
        isTrending: true,
        isAntiTarnish: true,
        isActive: true,
        tags: ['Men', 'Chain', 'Cuban Link', 'Gold', 'Waterproof'],
        createdAt: new Date().toISOString(),
      },
      {
        _id: 'prod_men_3',
        name: 'Titanium Helix Byzantine Chain',
        slug: 'titanium-helix-byzantine-chain',
        category: 'Chains',
        subCategory: 'Chains',
        gender: 'men',
        price: 2199,
        originalPrice: 3899,
        discount: 44,
        description: 'An intricate interlocking Byzantine weave inspired by royal armor. Features an ultra-secure custom lobster clasp and hypoallergenic finish.',
        shortDescription: 'Intricate royal weave necklace in raw titanium steel.',
        images: [
          'https://images.unsplash.com/photo-1611591475103-4fa1b7765a7f?auto=format&fit=crop&w=800&q=80',
        ],
        stock: 12,
        material: 'Pure Grade-5 Titanium & Stainless Steel',
        finish: 'Smoked Gunmetal Finish',
        sizes: ['22 inch'],
        rating: 4.9,
        numReviews: 34,
        isNewArrival: true,
        isBestseller: false,
        isTrending: true,
        isAntiTarnish: true,
        isActive: true,
        tags: ['Men', 'Chains', 'Titanium', 'Gunmetal'],
        createdAt: new Date().toISOString(),
      },
      {
        _id: 'prod_men_4',
        name: 'Nordic Braided Leather & Steel Cuff',
        slug: 'nordic-braided-leather-steel-cuff',
        category: 'Bracelets',
        subCategory: 'Bracelets',
        gender: 'men',
        price: 1399,
        originalPrice: 2499,
        discount: 44,
        description: 'Supple full-grain Italian leather double-braided with a brushed magnetic latch made of rust-proof steel.',
        shortDescription: 'Italian calfskin leather with magnetic brushed steel clasp.',
        images: [
          'https://images.unsplash.com/photo-1611591475103-4fa1b7765a7f?auto=format&fit=crop&w=800&q=80',
        ],
        stock: 20,
        material: 'Genuine Italian Leather & 316L Steel',
        finish: 'Midnight Black & Brushed Silver',
        sizes: ['19cm (Medium)', '21cm (Large)'],
        rating: 4.7,
        numReviews: 29,
        isNewArrival: false,
        isBestseller: true,
        isTrending: false,
        isAntiTarnish: true,
        isActive: true,
        tags: ['Men', 'Bracelets', 'Leather', 'Magnetic'],
        createdAt: new Date().toISOString(),
      },
      {
        _id: 'prod_men_5',
        name: 'Imperium Gold Signet Ring',
        slug: 'imperium-gold-signet-ring',
        category: 'Rings',
        subCategory: 'Rings',
        gender: 'men',
        price: 1299,
        originalPrice: 2199,
        discount: 41,
        description: 'A contemporary take on the classic aristocratic signet ring. Flat polished table with subtle beveled edges and comfort-fit inner band.',
        shortDescription: 'Solid signet ring with 18K gold coating and comfort-fit ergonomics.',
        images: [
          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=80',
        ],
        stock: 30,
        material: 'Surgical Steel with 18K PVD Gold',
        finish: 'Satin & Mirror Polish',
        sizes: ['US 8', 'US 9', 'US 10', 'US 11'],
        rating: 4.8,
        numReviews: 41,
        isNewArrival: true,
        isBestseller: true,
        isTrending: true,
        isAntiTarnish: true,
        isActive: true,
        tags: ['Men', 'Rings', 'Signet', '18K Gold'],
        createdAt: new Date().toISOString(),
      },
      {
        _id: 'prod_men_6',
        name: 'Sovereign Reversible Leather Belt',
        slug: 'sovereign-reversible-leather-belt',
        category: 'Belts',
        subCategory: 'Belts',
        gender: 'men',
        price: 1799,
        originalPrice: 2999,
        discount: 40,
        description: 'Handcrafted top-grain leather with a dual-sided design (Black / Rich Tan). Fitted with a micro-ratchet sliding buckle for zero-hole bespoke fitting.',
        shortDescription: 'Dual-sided top grain leather with micro-adjust sliding buckle.',
        images: [
          'https://images.unsplash.com/photo-1624222247344-550fb60583dc?auto=format&fit=crop&w=800&q=80',
        ],
        stock: 15,
        material: 'Top-Grain Leather & Zinc Alloy Buckle',
        finish: 'Brushed Platinum Chrome',
        sizes: ['Waist 30-36', 'Waist 38-44'],
        rating: 4.9,
        numReviews: 24,
        isNewArrival: false,
        isBestseller: true,
        isTrending: false,
        isAntiTarnish: true,
        isActive: true,
        tags: ['Men', 'Belts', 'Leather', 'Reversible'],
        createdAt: new Date().toISOString(),
      },

      // WOMEN
      {
        _id: 'prod_women_1',
        name: 'Celestial Aurora Pearl Chandbali',
        slug: 'celestial-aurora-pearl-chandbali',
        category: 'Earrings',
        subCategory: 'Earrings',
        gender: 'women',
        price: 1699,
        originalPrice: 2899,
        discount: 41,
        description: 'Heirloom-grade crescent moon chandbalis cascading with natural freshwater pearls and sparkling 5A cubic zirconia stones. Light-as-air ergonomics ensure zero ear strain.',
        shortDescription: 'Crescent moon chandbali earrings with freshwater seed pearls.',
        images: [
          'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1600003014755-ba31aa59c4b6?auto=format&fit=crop&w=800&q=80',
        ],
        stock: 22,
        material: '18K Yellow Gold Plating over Brass & Natural Pearls',
        finish: 'Antique Gold Glow',
        sizes: ['Free Size (6.5cm drop)'],
        rating: 4.9,
        numReviews: 78,
        isNewArrival: true,
        isBestseller: true,
        isTrending: true,
        isAntiTarnish: true,
        isActive: true,
        tags: ['Women', 'Earrings', 'Chandbali', 'Pearls', 'Wedding'],
        createdAt: new Date().toISOString(),
      },
      {
        _id: 'prod_women_2',
        name: 'Mayura Heirloom Saree Waist Brooch',
        slug: 'mayura-heirloom-saree-waist-brooch',
        category: 'Saree Accessories',
        subCategory: 'Saree Accessories',
        gender: 'women',
        price: 1499,
        originalPrice: 2499,
        discount: 40,
        description: 'Exquisitely sculpted peacock motif saree pleat brooch encrusted with ruby-hued baguettes and hanging jhumki bells. Secures your saree pleats seamlessly without fabric snags.',
        shortDescription: 'Peacock motif saree brooch with delicate jhumki droplets.',
        images: [
          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=800&q=80',
        ],
        stock: 16,
        material: 'Micro-plated 22K Gold & Snag-free Pin Mechanism',
        finish: 'Royal Temple Gold',
        sizes: ['Standard'],
        rating: 4.9,
        numReviews: 35,
        isNewArrival: true,
        isBestseller: true,
        isTrending: true,
        isAntiTarnish: true,
        isActive: true,
        tags: ['Women', 'Saree Accessories', 'Brooch', 'Peacock', 'Festive'],
        createdAt: new Date().toISOString(),
      },
      {
        _id: 'prod_women_3',
        name: 'Riviera Dual-Chain Seashell Anklet',
        slug: 'riviera-dual-chain-seashell-anklet',
        category: 'Anklets',
        subCategory: 'Anklets',
        gender: 'women',
        price: 899,
        originalPrice: 1499,
        discount: 40,
        description: 'Double strand dainty payal with laser-engraved seashell charms and shimmer beads. 100% tarnish-free, sweat-proof, and comfortable enough for 24/7 wear.',
        shortDescription: 'Water-resistant double chain payal with delicate seashell drops.',
        images: [
          'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?auto=format&fit=crop&w=800&q=80',
        ],
        stock: 35,
        material: '316L Stainless Steel & 18K Rose Gold Plating',
        finish: 'High Polish Rose Gold',
        sizes: ['Adjustable (21cm + 5cm extender)'],
        rating: 4.8,
        numReviews: 53,
        isNewArrival: false,
        isBestseller: true,
        isTrending: true,
        isAntiTarnish: true,
        isActive: true,
        tags: ['Women', 'Anklets', 'Payal', 'Rose Gold', 'Anti-Tarnish'],
        createdAt: new Date().toISOString(),
      },
      {
        _id: 'prod_women_4',
        name: 'Luxe Pearl Jeans Waist Adjuster',
        slug: 'luxe-pearl-jeans-waist-adjuster',
        category: 'Jeans Adjuster',
        subCategory: 'Jeans Adjuster',
        gender: 'women',
        price: 799,
        originalPrice: 1299,
        discount: 38,
        description: 'A revolutionary aesthetic accessory that tightens loose denim waistbands instantly while looking like a high-fashion jewellery pin. Tool-free clip mechanism.',
        shortDescription: 'Jewelled pearl waist cincher pin for perfect denim fitting.',
        images: [
          'https://images.unsplash.com/photo-1598560917505-59a3ad559071?auto=format&fit=crop&w=800&q=80',
        ],
        stock: 40,
        material: 'Reinforced Zinc Alloy with Acrylic Pearl & Crystals',
        finish: 'Glossy Gold & Pearl Ivory',
        sizes: ['Set of 2 Pairs'],
        rating: 4.9,
        numReviews: 89,
        isNewArrival: true,
        isBestseller: true,
        isTrending: true,
        isAntiTarnish: true,
        isActive: true,
        tags: ['Women', 'Jeans Adjuster', 'Pearl', 'Fashion Hack'],
        createdAt: new Date().toISOString(),
      },
      {
        _id: 'prod_women_5',
        name: 'Serenade Tennis Bracelet with Baguette Cz',
        slug: 'serenade-tennis-bracelet-with-baguette-cz',
        category: 'Bracelets & Bangles',
        subCategory: 'Bracelets & Bangles',
        gender: 'women',
        price: 1999,
        originalPrice: 3499,
        discount: 43,
        description: 'A continuous stream of hand-prong-set baguette and round brilliant cubic zirconia crystals. Glints with diamond fire under sunlight or ambient evening dinner lights.',
        shortDescription: 'Prong-set baguette diamond simulants with double safety clasp.',
        images: [
          'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?auto=format&fit=crop&w=800&q=80',
        ],
        stock: 14,
        material: 'Sterling Silver 925 Core & Rhodium / 18K Gold Plating',
        finish: 'Brilliant Diamond Polish',
        sizes: ['6.5 inch', '7.0 inch', '7.5 inch'],
        rating: 5.0,
        numReviews: 44,
        isNewArrival: false,
        isBestseller: true,
        isTrending: true,
        isAntiTarnish: true,
        isActive: true,
        tags: ['Women', 'Bracelets', 'Tennis Bracelet', 'Luxury', 'Diamonds'],
        createdAt: new Date().toISOString(),
      },
      {
        _id: 'prod_women_6',
        name: 'Constellation Crawler Upper Lobe Earring',
        slug: 'constellation-crawler-upper-lobe-earring',
        category: 'Upper Lobe Earrings',
        subCategory: 'Upper Lobe Earrings',
        gender: 'women',
        price: 899,
        originalPrice: 1499,
        discount: 40,
        description: 'Curves naturally along the outer ear ridge without requiring multiple piercings. Features a row of graduated celestial starburst crystals.',
        shortDescription: 'Graduated starburst crystal crawler for upper ear cartilage.',
        images: [
          'https://images.unsplash.com/photo-1600003014755-ba31aa59c4b6?auto=format&fit=crop&w=800&q=80',
        ],
        stock: 28,
        material: 'Hypoallergenic Titanium with White Gold Dipping',
        finish: 'Mirror Platinum',
        sizes: ['Single Piece (Left Ear)', 'Single Piece (Right Ear)', 'Pair'],
        rating: 4.7,
        numReviews: 31,
        isNewArrival: true,
        isBestseller: false,
        isTrending: true,
        isAntiTarnish: true,
        isActive: true,
        tags: ['Women', 'Upper Lobe', 'Ear Cuff', 'Constellation'],
        createdAt: new Date().toISOString(),
      },
      {
        _id: 'prod_women_7',
        name: 'Solstice Oval Solitaire Ring',
        slug: 'solstice-oval-solitaire-ring',
        category: 'Rings',
        subCategory: 'Rings',
        gender: 'women',
        price: 1399,
        originalPrice: 2299,
        discount: 39,
        description: 'An elongated 2.5 carat equivalent crushed-ice oval crystal perched on a dainty pavé band. Subtle hidden halo underneath elevates the stone for maximum light reflection.',
        shortDescription: 'Crushed-ice oval solitaire on a micro-pavé band.',
        images: [
          'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=800&q=80',
        ],
        stock: 20,
        material: '18K Yellow Gold Dip over Sterling Silver 925',
        finish: 'Radiant Polish',
        sizes: ['US 5', 'US 6', 'US 7', 'US 8', 'Adjustable'],
        rating: 4.9,
        numReviews: 67,
        isNewArrival: false,
        isBestseller: true,
        isTrending: true,
        isAntiTarnish: true,
        isActive: true,
        tags: ['Women', 'Rings', 'Solitaire', 'Oval Cut', 'Engagement'],
        createdAt: new Date().toISOString(),
      },
      {
        _id: 'prod_women_8',
        name: 'Chandrika Non-Piercing Clip Nath',
        slug: 'chandrika-non-piercing-clip-nath',
        category: 'Nose Rings',
        subCategory: 'Nose Rings',
        gender: 'women',
        price: 849,
        originalPrice: 1399,
        discount: 39,
        description: 'Traditional Maharashtrian & North Indian bridal clip-on nath adorned with Basra pearl beads and emerald stone droplets. Easy silicone clip ensures pain-free all-day grip.',
        shortDescription: 'Pain-free clip-on traditional Indian nath with pearls and rubies.',
        images: [
          'https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?auto=format&fit=crop&w=800&q=80',
        ],
        stock: 30,
        material: 'Micro Gold Plated Brass & Hand-selected Seed Pearls',
        finish: 'Traditional Jadau Gold',
        sizes: ['Free Size Clip-on'],
        rating: 4.8,
        numReviews: 39,
        isNewArrival: true,
        isBestseller: true,
        isTrending: false,
        isAntiTarnish: true,
        isActive: true,
        tags: ['Women', 'Nose Rings', 'Nath', 'Clip-On', 'Bridal'],
        createdAt: new Date().toISOString(),
      },
    ];

    this.orders = [
      {
        _id: 'order_seed_001',
        orderId: 'OJ-26-441920',
        user: {
          _id: 'user_customer_001',
          name: 'Riya Sharma',
          email: 'riya.sharma@example.com',
          phone: '+91 9123456780',
        },
        orderItems: [
          {
            product: 'prod_women_1',
            name: 'Celestial Aurora Pearl Chandbali',
            slug: 'celestial-aurora-pearl-chandbali',
            image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80',
            price: 1699,
            quantity: 1,
            size: 'Free Size (6.5cm drop)',
          },
        ],
        shippingAddress: {
          fullName: 'Riya Sharma',
          phone: '+91 9123456780',
          house: 'Flat 402, Lotus Grand Residences',
          street: 'Koramangala 4th Block',
          area: 'Near Sony World Signal',
          city: 'Bengaluru',
          state: 'Karnataka',
          pincode: '560034',
          landmark: 'Opposite Starbucks',
        },
        paymentMethod: 'razorpay',
        paymentResult: {
          id: 'pay_sample_12908',
          status: 'Captured',
          razorpay_order_id: 'order_sample_8821',
          razorpay_payment_id: 'pay_sample_12908',
          razorpay_signature: 'verified',
        },
        itemsPrice: 1699,
        taxPrice: 0,
        shippingPrice: 0,
        discountAmount: 0,
        couponCode: '',
        oceanPointsUsed: 0,
        oceanPointsEarned: 16,
        totalPrice: 1699,
        isPaid: true,
        paidAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        orderStatus: 'Shipped',
        statusTimeline: [
          {
            status: 'Confirmed',
            note: 'Order confirmed and paid via Razorpay.',
            timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
          },
          {
            status: 'Processing',
            note: 'Passed Ocean Jewel 12-point quality inspection & gift wrapped.',
            timestamp: new Date(Date.now() - 1.5 * 24 * 60 * 60 * 1000).toISOString(),
          },
          {
            status: 'Shipped',
            note: 'Dispatched via BlueDart Luxury Express. AWB #OJ-TRK-9812401',
            timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
          },
        ],
        shipmentTracking: {
          courier: 'BlueDart Luxury Express',
          trackingNumber: 'OJ-TRK-9812401',
          trackingUrl: 'https://shiprocket.co/tracking/OJ-TRK-9812401',
          estimatedDelivery: 'Tomorrow by 4:00 PM',
        },
        createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      },
    ];

    this.reviews = [
      {
        _id: 'rev_001',
        user: 'user_customer_001',
        userName: 'Riya Sharma',
        product: 'prod_women_1',
        rating: 5,
        title: 'Breathtaking craftsmanship & zero tarnish!',
        comment: 'I have been wearing the Celestial Aurora Pearl Chandbalis for over 2 months now. The anti-tarnish finish is 100% genuine — no discoloration even after perfumes and water. Packaging arrived in a gorgeous satin box!',
        isVerifiedPurchase: true,
        createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      },
    ];

    console.log('💎 [Ocean Jewel Data Store] Initialized with 13 categories, 14 luxury products, coupons, and test users.');
  }
}

export const mockStore = new MockStore();
